wslutilities/wslu

- scripts/builder-deb.sh
- scripts/builder-rpm.sh
- src/wslusc.sh
> wslu 1.5-2

- src/wslu-header
- src/wslusc.sh
Suggestions for improvements to help language generally and also in wslusc
> Suggestions for improvements to help language generally and also in wslusc

- src/wslupath.sh
This is only a POC. This is my proposed way to maintain wslupath compatibility without affect future versions maintainability.
> Fix -H for root change

- tests/wslupath.bats
> Fix one test failing on Windows

- .circleci/config.yml
- [x ] New feature (non-breaking change which adds functionality)
- [x ] I have read Code of Conduct and Contributing documentations.
- [x ] My code follows the code style of this project.
> Added Oracle Linux and Elementary OS to CircleCI/Packagecloud

- extras/build/alpine/APKBUILD
- extras/build/arch/PKGBUILD
- src/wslu-header
- src/wslusc.sh
wslusc: fix a bug that failed to create the "wslu" folder.
> 2.1.1 fix update

- extras/build/alpine/APKBUILD
- extras/build/arch/PKGBUILD
- src/wslu-header
- src/wslusc.sh
- wslusc: fixed wrong --resize value (#76)
> wslu 2.2.1

- README.md
> Install wslu from the official archive on Ubuntu

- extras/build/alpine/APKBUILD
- extras/build/arch/PKGBUILD
- src/wslfetch.sh
- src/wslu-header
- **wslufetch**: --line parameter fixes
> wslu 2.3.2

- .circleci/config.yml
> Add fedora31 support

- Makefile
- extras/build/alpine/APKBUILD
- extras/build/arch/PKGBUILD
- src/wslu-header
- src/wslusc.sh
This is the pull request for the release of wslu 2.3.3. 
**N/A**
- **Project**:  Add support for Fedora 31
**N/A**
- **Project**: fix an issue in generating `~/.config/baseexec`
- **wslusc**:  fix an issue that will cause generated shortcut cannot be opened for some users
> wslu 2.3.3

- README.hans.md
- README.hant.md
- README.md
- extras/build/alpine/APKBUILD
- extras/build/arch/PKGBUILD
- src/wslu-header
This is the pull request for the release of wslu 2.3.4. 
- small documentation update
**N/A**
**N/A**
- **Project**: fix an issue in handling dirty output in regenerate `baseexec` (fixes https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/issues/64 and https://github.com/wslutilities/wslu/commit/8d396c88381b5d4499e6ed5ea87394a7c6c191cf#r36694705)
> wslu 2.3.4

- src/wslu-header
> This is the pull request for the release of wslu 2.3.5
N/A
N/A
N/A
wslu: imported distro cannot be properly handled by `baseexec_gen` ( fixes #104 )
> wslu 2.3.5

- src/applications/wslview.desktop
Typo fix in `src/applications/wslview.desktop`
* \`MimeType\` option was incorrectly written as \`MimeTypes\`.
> wslview.desktop fix for typo

- README.md
> Update instructions for Pengwin Enterprise and Fedora Remix

- configure.sh
- docs/wslsys.1
- src/wslfetch.sh
- src/wslsys.sh
Added ipv4 address to wslfetch info as suggested in #139
> Adds ipv4 address to wslfetch

- README.hans.md
Fix translation errors
remove unnecessary “需要”。
删除多余的 “需要”。
> Fix translation errors

- README.md
Fix typo in `README.md`.
Doanload → Download
> Fix typo: Doanload → Download

- src/wslu-header
> still need to test it on a special machine that uses a different encoding.
This fixes an encoding issue that caused Environment to fail to transfer with proper encodings.
> LTS: Encoding issue (fixes #162)

- README.md
> Add instructions for Fedora

- docs/wslu.7
- src/etc/conf
- src/wslusc.sh
> native gui support

- extras/build/rpm/wslu.spec
> Fedora 34 rpmbuild fix

- extras/build/rpm/wslu.spec
> pkg: Further rpm spec update for Fedora 34

- extras/build/rpm/wslu.spec
> Arch Linux Quick Patch

- README.md
> Corrected the name of Fedora Remix and Pengwin Enterprise

- src/etc/conf
- src/wslu-header
- src/wslusc.sh
> wslusc improvement: smart iconfinder

- README.md
> Improve instructions for CentOS 8 and RHEL 8

- src/wslu-header
> Fixed typo in comments

- src/wslview.sh
add shift; code for -E flag
Fix wslview -E|--engine error
Add "shift;" code for -E|--engine) options
> Breaking change (fix or feature that would cause existing functionality to not work as expected) are no longer accepted
> Fix wslview -E error

- Makefile
> Breaking change (fix or feature that would cause existing functionality to not work as expected) are no longer accepted
> Install desktop files in the correct XDG location

- .github/workflows/pkgdeploy.yaml
Pengwin has a new bookworm repository. The change makes wslu available in this repo as well
> Breaking change (fix or feature that would cause existing functionality to not work as expected) are no longer accepted
> Deploy to Pengwin debian bookworm as well

- docs/wslfetch.1
- docs/wslgsu.1
- docs/wslsys.1
- docs/wslu.7
This pull request fixes some of the typos under docs folder. I request repository maintainers to review and merge it.
Typos are:
cutom -> custom 
autoamtically -> automatically 
realease -> release 
disply -> display 
defualt -> default 
> Breaking change (fix or feature that would cause existing functionality to not work as expected) are no longer accepted
> docs: Fixed typos

- Makefile
Don't remove file if name matches `wslinfo`. Fixes #316
> build: [GH #316 ] prevent removal of wslinfo
